version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hex_golang
      - POSTGRES_URL=jdbc:postgresql://localhost:5432/hex_golang
    ports:
      - '5432:5432'
    volumes:
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql